platform :ios, "9.0"

workspace '../../ArchitectWorkspace'

# use_frameworks!

target 'Architect' do
    pod 'HandyJSON', '~> 4.2.0'
    pod 'Moya', '~> 12.0'
end

target 'ArchitectTests' do
    pod 'HandyJSON', '~> 4.2.0'
    pod 'Moya', '~> 12.0'
end

target 'ArchitectUITests' do
    pod 'HandyJSON', '~> 4.2.0'
    pod 'Moya', '~> 12.0'
end
